service: serverless-flask

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-deployment-bucket
  - serverless-dotenv-plugin

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-1
  deploymentBucket:
    name: serverless-deployment-gw-2
  environment:
    GKG_API_KEY: ${env:GKG_API_KEY}

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
